[package]
name = "zsft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rc_wrap = { path="../rc_wrap" }

[lib]
name = "zsft"
path = "src/lib.rs"
